const data = {
    songsList: [
        
        {
            id:1,
            url:"./assets/songs/euphoria.mp3",
            title:"euphoria",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"2:16"
        },
        {
            id:2,
            url:"./assets/songs/fun-life.mp3",
            title:"fun-life",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:50"
        },
       
        {
            id:3,
            url:"./assets/songs/hard-step.mp3",
            title:"hard step",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:36"
        },
       
        {
            id:4,
            url:"./assets/songs/hip-hop-rock.mp3",
            title:"hip-hop-rock",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:20"
        },
       
        {
            id:5,
            url:"./assets/songs/password-infinity.mp3",
            title:"password-infinity",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"2:26"
        },
        {
            id:6,
            url:"./assets/songs/positive-way.mp3",
            title:"positive-way",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"2:00"
        },
        {
            id:7,
            url:"./assets/songs/powerful-energetic.mp3",
            title:"powerful-energetic",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:57"
        },
        
       
        {
            id:8,
            url:"./assets/songs/spirit-of-success.mp3",
            title:"spirit-of-success",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"2:09"
        },
        {
            id:9,
            url:"./assets/songs/stylish-sexy-beat.mp3",
            title:"stylish-sexy-beat",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:19"
        },
        {
            id:10,
            url:"./assets/songs/success-story.mp3",
            title:"success-story",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"2:09"
        },
        {
            id:11,
            url:"./assets/songs/summer-future.mp3",
            title:"summer-future",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:14"
        },
        {
            id:12,
            url:"./assets/songs/powerful-beat-121791.mp3",
            title:"powerful-beat-121791",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:14"
        },
        {
            id:13,
            url:"./assets/songs/smoke-143172.mp3",
            title:"smoke-143172",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:59"
        },
        {
            id:14,
            url:"./assets/songs/lofi-chill.mp3",
            title:"lofi-chill",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:08"
        },
        {
            id:15,
            url:"./assets/songs/good-night-160166.mp3",
            title:"good-night-160166",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"2:27"
        },
        {
            id:16,
            url:"./assets/songs/abstract-future.mp3",
            title:"abstract-future",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:32"
        },
        {
            id:17,
            url:"./assets/songs/titanium-170190.mp3",
            title:"titanium-170190",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:46"
        },
        {
            id:18,
            url:"./assets/songs/powerful-beat-121791.mp3",
            title:"powerful-beat-121791",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:14"
        },
        {
            id:19,
            url:"./assets/songs/drop-it-124014.mp3",
            title:"drop-it-124014",
            artist:"unknown",
            coverUrl:"unknown",
            duration:"1:42"
        },
        
    ]
};

export default data;